import type { Metadata } from "next";
import "./globals.css";
import { gilroy } from './fonts';

import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Raoua-Tachnical-Test",
  description: "Generated by NextJs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${gilroy.variable} ${inter.variable} hide-scrollbar`}  >
      <body
        className={` hide-scrollbar  antialiased`}
      >
        <div className="w-full max-w-[1440px] mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
